# Generated by Django 4.1.5 on 2023-01-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Category')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Game name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Review')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Post created')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Post updated')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publish')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Game list',
                'verbose_name_plural': 'Game list',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
