# Generated by Django 4.1.5 on 2023-01-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='cat',
            new_name='category',
        ),
    ]
